const { sequelize, DataTypes } = require('../../../infrastructure/config/database_config')

const Employee = sequelize.define('employee', {
    id:{
        type:DataTypes.BIGINT,
        primaryKey:true,
        allowNull:false,
        autoIncrement:true,
        unique:true
    },
    name:{
        type:DataTypes.STRING,
        allowNull:false
    },
    last_name:{
        type:DataTypes.STRING,
        allowNull:false
    },
    gender:{
        type:DataTypes.STRING,
        allowNull:true
    },
    occupation:{
        type:DataTypes.STRING,
        allowNull:false
    },
    email:{
        type:DataTypes.STRING,
        allowNull:false
    },
    employee_code:{
        type:DataTypes.STRING,
        allowNull:true
    },
    birth_date:{
        type:DataTypes.DATE,
        allowNull:false
    },
    rg:{
        type:DataTypes.STRING,
        allowNull:false
    },
    cpf:{
        type:DataTypes.STRING,
        allowNull:false
    },
    ctps:{
        type:DataTypes.STRING,
        allowNull:false
    },
    pis_pasep:{
        type:DataTypes.STRING,
        allowNull:false
    },
    initial_salary:{
        type:DataTypes.FLOAT,
        allowNull:true
    },
    current_salary:{
        type:DataTypes.FLOAT,
        allowNull:true
    },
    phone_number:{
        type:DataTypes.STRING,
        allowNull:true
    },
    cellphone_number:{
        type:DataTypes.STRING,
        allowNull:true
    },
    cep:{
        type:DataTypes.STRING,
        allowNull:false
    },
    address:{
        type:DataTypes.STRING,
        allowNull:false
    },
    house:{
        type:DataTypes.STRING,
        allowNull:false
    },
    status:{
        type:DataTypes.STRING,
        allowNull:false
    },
    opt_transportation_vouchers:{
        type:DataTypes.BOOLEAN,
        allowNull:true
    },
    registry_book:{
        type:DataTypes.STRING,
        allowNull:true
    },
    active:{
        type:DataTypes.BOOLEAN
    }

})

module.exports = {
    Employee
}